"""added name column to users table

Revision ID: 008b9faf6f43
Revises: 0ce9b698587f
Create Date: 2024-07-19 14:57:00.042707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008b9faf6f43'
down_revision = '0ce9b698587f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
