"""Initial migration

Revision ID: 0ce9b698587f
Revises: 
Create Date: 2024-07-19 14:29:19.821537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce9b698587f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_ons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flavors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ice_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_drinks_category_id_categories')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotdogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('with_chili', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_hotdogs_category_id_categories')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shaved_ices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('ice_size_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_shaved_ices_category_id_categories')),
    sa.ForeignKeyConstraint(['ice_size_id'], ['ice_sizes.id'], name=op.f('fk_shaved_ices_ice_size_id_ice_sizes')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_snacks_category_id_categories')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combo_flavors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('shaved_ice_id', sa.Integer(), nullable=True),
    sa.Column('flavor_id', sa.Integer(), nullable=True),
    sa.Column('add_on_id', sa.Integer(), nullable=True),
    sa.Column('cream_id', sa.Integer(), nullable=True),
    sa.Column('ice_size_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['add_on_id'], ['add_ons.id'], name=op.f('fk_combo_flavors_add_on_id_add_ons')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_combo_flavors_category_id_categories')),
    sa.ForeignKeyConstraint(['cream_id'], ['creams.id'], name=op.f('fk_combo_flavors_cream_id_creams')),
    sa.ForeignKeyConstraint(['flavor_id'], ['flavors.id'], name=op.f('fk_combo_flavors_flavor_id_flavors')),
    sa.ForeignKeyConstraint(['ice_size_id'], ['ice_sizes.id'], name=op.f('fk_combo_flavors_ice_size_id_ice_sizes')),
    sa.ForeignKeyConstraint(['shaved_ice_id'], ['shaved_ices.id'], name=op.f('fk_combo_flavors_shaved_ice_id_shaved_ices')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toppings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotdog_id', sa.Integer(), nullable=True),
    sa.Column('condiment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condiment_id'], ['condiments.id'], name=op.f('fk_toppings_condiment_id_condiments')),
    sa.ForeignKeyConstraint(['hotdog_id'], ['hotdogs.id'], name=op.f('fk_toppings_hotdog_id_hotdogs')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toppings')
    op.drop_table('combo_flavors')
    op.drop_table('snacks')
    op.drop_table('shaved_ices')
    op.drop_table('hotdogs')
    op.drop_table('drinks')
    op.drop_table('users')
    op.drop_table('ice_sizes')
    op.drop_table('flavors')
    op.drop_table('creams')
    op.drop_table('condiments')
    op.drop_table('categories')
    op.drop_table('add_ons')
    # ### end Alembic commands ###
